# Generated by Django 3.2 on 2024-06-15 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 15, 16, 28, 45, 341140, tzinfo=utc))),
            ],
        ),
    ]
