# Generated by Django 3.2 on 2024-06-15 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPIs', '0002_contractus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 16, 46, 12, 246664, tzinfo=utc)),
        ),
    ]
