# Generated by Django 3.2 on 2024-06-15 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPIs', '0006_alter_contractus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractus',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractus',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 22, 15, 18, 35428, tzinfo=utc)),
        ),
    ]
